baseurl = "https://z-r0crypt.github.io"
title = "Security Notes"
languageCode = "en-us"
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10
enableRobotsTXT = true
canonifyURLs = true

[author]
    name = "Z-r0crypt"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"
    tag = "tags"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    sidebar = "left"
    # Used when a given page doesn't set its own.
    defaultDescription = "Security notes for learning and sharing"
    defaultKeywords = "offsec, OSCP, OSCE, OSWE, OSEP, Appsec, ExploitDev, Infosec, Security, BugBounty, Bug Hunting, Penetration Testing, Pentest, Fuzzing, Red Team, OSINT"

    # Hide estimated reading time for posts.
    # Default (if omitted) is false.
    hideReadingTime = true

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-08"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Optional additional custom CSS file URL, will override other styles.
    customCSS = ""

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Security ..."

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Blog"

    # Metadata used to drive integrations.
    googleAnalytics = "UA-153171451-1"
    google_verify = "lKxcocybGM-2fyrJhswx85Oxp6S4sqLCd-M0H34O-Ko"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/z-r0crypt"
#    bitbucket = ""
#    stackOverflow = ""
    linkedin = "https://linkedin.com/in/vbtr"
#    googleplus = ""
#    facebook = ""
    twitter = "https://twitter.com/zer0crypt"
#    youtube = ""

    # Other social-like sidebar links
    #rss = false  # switch to true to enable RSS icon link
    #flattr = ""  # populate with your flattr uid


[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/categories/"
    name = "Categories"
    weight = 3

[[menu.main]]
    url = "/about"
    name = "About"
    weight = 4

